saving recent updates (mostly around debian)

diff --git a/functionrc b/functionrc
--- a/functionrc
+++ b/functionrc
@@ -70,91 +70,89 @@ function tm() {
 # VirtualBox Fuctions
 #############################################################
 _vb_cmd="VBoxManage"
-
-function _vb_help {
-  echo "Usage: vb ACTION VM"
-  echo " "
-  echo "Actions"
-  echo "- up|start        start/restart/wake"
-  echo "- pause           pause"
-  echo "- sleep           sleep"
-  echo "- down|stop       graceful shutdown"
-  echo "- kill|halt|off   forceful shutdown"
-  echo "- status|state    minimial status "
-  echo "- info|describe   verbose status "
-  echo "- debug|setup     start with gui for setup or troubleshooting"
-  echo "- ssh             attempt to ssh to guest vbox (fragile)"
-  echo "- help            show this message "
-  echo " "
-  echo "VMs"
-  echo "$($_vb_cmd list vms| grep -v boot2docker-vm)"
-  echo " "
-}
-
-function _vb_ssh {
-}
-
-function vb {
-  if ! test "$(which $_vb_cmd)"; then
-    echo "ERROR: VirtualBox not found"
+if test "$(which $_vb_cmd 2> /dev/null)"; then
+  function _vb_help {
+    echo "Usage: vb ACTION VM"
     echo " "
-    _vb_help
-    return 1
-  fi
-
-  if [[ "$1" = "" || "$1" = "help" ]]; then
-    _vb_help
-    return 0
-  fi
-
-  local guest=$2
-  # I am setting a default here for myself, you might want to remove this if
-  # you're not me.
-  test "$guest" || guest=Debian
-
-  # Error checking for those that remove the default guest lines above.
-  if ! test "$guest"; then
-    echo "ERROR: VirtualBox VM required"
+    echo "Actions"
+    echo "- up|start        start/restart/wake"
+    echo "- pause           pause"
+    echo "- sleep           sleep"
+    echo "- down|stop       graceful shutdown"
+    echo "- kill|halt|off   forceful shutdown"
+    echo "- status|state    minimial status "
+    echo "- info|describe   verbose status "
+    echo "- debug|setup     start with gui for setup or troubleshooting"
+    echo "- ssh             attempt to ssh to guest vbox (fragile)"
+    echo "- help            show this message "
     echo " "
-    _vb_help
-    return 1
-  fi
+    echo "VMs"
+    echo "$($_vb_cmd list vms| grep -v boot2docker-vm)"
+    echo " "
+  }
 
-  case $1 in
-  up|start)
-    $_vb_cmd controlvm $guest resume || $_vb_cmd startvm $guest --type headless;;
-  debug|setup)
-    $_vb_cmd startvm $guest --type gui;;
-  down|stop)
-    $_vb_cmd controlvm $guest acpipowerbutton;;
-  pause)
-    $_vb_cmd controlvm $guest pause;;
-  sleep)
-    $_vb_cmd controlvm $guest acpisleepbutton;;
-  kill|halt|off)
-    $_vb_cmd controlvm $guest poweroff;;
-  status|state)
-    $_vb_cmd showvminfo $guest | grep State;;
-  info|describe)
-    $_vb_cmd showvminfo $guest | less;;
-  ssh)
-    # Fragile at best
-    #
-    # I setup port forwarding with this to get this working:
-    #
-    # $ VBoxManage modifyvm GuestBox --natpf1 "ssh,tcp,,2222,,22"
-    #
-    # USER=guestuser vb ssh GuestBox
-    test "$USER" || USER=`whoami`
-    ssh $USER@localhost -p $(VBoxManage showvminfo $guest | grep Rule | grep ssh | awk -F',' '{print $4}' | awk -F'=' '{ print $NF}');;
-  *)
-    _vb_help
-  esac
-}
-alias vm=vb
-puts "+ initialized vb function"
-puts "+    alias: 'vm'"
-puts "+ Usage: vm ACTION VM"
+  function vb {
+    if ! test "$(which $_vb_cmd)"; then
+      echo "ERROR: VirtualBox not found"
+      echo " "
+      _vb_help
+      return 1
+    fi
+
+    if [[ "$1" = "" || "$1" = "help" ]]; then
+      _vb_help
+      return 0
+    fi
+
+    local guest=$2
+    # I am setting a default here for myself, you might want to remove this if
+    # you're not me.
+    test "$guest" || guest=Debian
+
+    # Error checking for those that remove the default guest lines above.
+    if ! test "$guest"; then
+      echo "ERROR: VirtualBox VM required"
+      echo " "
+      _vb_help
+      return 1
+    fi
+
+    case $1 in
+    up|start)
+      $_vb_cmd controlvm $guest resume || $_vb_cmd startvm $guest --type headless;;
+    debug|setup)
+      $_vb_cmd startvm $guest --type gui;;
+    down|stop)
+      $_vb_cmd controlvm $guest acpipowerbutton;;
+    pause)
+      $_vb_cmd controlvm $guest pause;;
+    sleep)
+      $_vb_cmd controlvm $guest acpisleepbutton;;
+    kill|halt|off)
+      $_vb_cmd controlvm $guest poweroff;;
+    status|state)
+      $_vb_cmd showvminfo $guest | grep State;;
+    info|describe)
+      $_vb_cmd showvminfo $guest | less;;
+    ssh)
+      # Fragile at best
+      #
+      # I setup port forwarding with this to get this working:
+      #
+      # $ VBoxManage modifyvm GuestBox --natpf1 "ssh,tcp,,2222,,22"
+      #
+      # USER=guestuser vb ssh GuestBox
+      test "$USER" || USER=`whoami`
+      ssh $USER@localhost -p $(VBoxManage showvminfo $guest | grep Rule | grep ssh | awk -F',' '{print $4}' | awk -F'=' '{ print $NF}');;
+    *)
+      _vb_help
+    esac
+  }
+  alias vm=vb
+  puts "+ initialized vb function"
+  puts "+    alias: 'vm'"
+  puts "+ Usage: vm ACTION VM"
+fi
 
 #############################################################
 # Encryption Fuctions
